### ISSUE TITLE
Version 2.x.x changes

### ISSUE THREAD

**Issue by Phil-Friderici** [Ericsson/puppet-module-postfix#21]
these changes will break backward compatibility:
- remove $template_main_cf, it makes no sense

**Comment by Phil-Friderici** [comment]
I would like to hard code this one. I think it's coming from the old idea to have your own templates that I have never seen to be used anyway.

**Comment by anders-larsson** [comment]
We're not using this functionality at all from what I can see. I haven't heard of anyone using it either.

I see no problem removing this functionality.

**Comment by Phil-Friderici** [comment]
will remove it :)
